import type { Restaurant, Food, Category, Offer } from './types'

export const categories: Category[] = [
  { id: 'c1', name: 'Pizza', image: '/images/food-pizza.png', icon: 'Pizza' },
  { id: 'c2', name: 'Burgers', image: '/images/food-burger.png', icon: 'Beef' },
  { id: 'c3', name: 'Biryani', image: '/images/food-biryani.png', icon: 'CookingPot' },
  { id: 'c4', name: 'Sushi', image: '/images/food-sushi.png', icon: 'Fish' },
  { id: 'c5', name: 'Healthy', image: '/images/food-salad.png', icon: 'Salad' },
  { id: 'c6', name: 'Pasta', image: '/images/food-pasta.png', icon: 'Wheat' },
  { id: 'c7', name: 'Desserts', image: '/images/food-dessert.png', icon: 'CakeSlice' },
  { id: 'c8', name: 'Drinks', image: '/images/food-smoothie.png', icon: 'CupSoda' },
]

export const restaurants: Restaurant[] = [
  {
    id: 'r1',
    name: 'Bella Napoli',
    slug: 'bella-napoli',
    image: '/images/food-pizza.png',
    cuisines: ['Italian', 'Pizza', 'Pasta'],
    rating: 4.6,
    deliveryTime: 25,
    priceForTwo: 450,
    diet: 'Veg',
    offer: '50% OFF up to $10',
    promoted: true,
    location: 'Downtown',
  },
  {
    id: 'r2',
    name: 'The Burger Yard',
    slug: 'the-burger-yard',
    image: '/images/food-burger.png',
    cuisines: ['American', 'Burgers', 'Fast Food'],
    rating: 4.4,
    deliveryTime: 20,
    priceForTwo: 350,
    diet: 'Non-Veg',
    offer: 'Free delivery',
    promoted: true,
    location: 'Midtown',
  },
  {
    id: 'r3',
    name: 'Spice Route',
    slug: 'spice-route',
    image: '/images/food-biryani.png',
    cuisines: ['Indian', 'Biryani', 'Curry'],
    rating: 4.7,
    deliveryTime: 35,
    priceForTwo: 500,
    diet: 'Non-Veg',
    offer: '20% OFF',
    location: 'Old Town',
  },
  {
    id: 'r4',
    name: 'Sakura House',
    slug: 'sakura-house',
    image: '/images/food-sushi.png',
    cuisines: ['Japanese', 'Sushi', 'Asian'],
    rating: 4.8,
    deliveryTime: 40,
    priceForTwo: 700,
    diet: 'Non-Veg',
    location: 'Harbor',
  },
  {
    id: 'r5',
    name: 'Green Bowl',
    slug: 'green-bowl',
    image: '/images/food-salad.png',
    cuisines: ['Healthy', 'Salads', 'Vegan'],
    rating: 4.5,
    deliveryTime: 18,
    priceForTwo: 400,
    diet: 'Veg',
    offer: 'Buy 1 Get 1',
    location: 'Riverside',
  },
  {
    id: 'r6',
    name: 'Pasta Fresca',
    slug: 'pasta-fresca',
    image: '/images/food-pasta.png',
    cuisines: ['Italian', 'Pasta', 'Continental'],
    rating: 4.3,
    deliveryTime: 30,
    priceForTwo: 480,
    diet: 'Veg',
    location: 'Downtown',
  },
  {
    id: 'r7',
    name: 'Sweet Ember',
    slug: 'sweet-ember',
    image: '/images/food-dessert.png',
    cuisines: ['Desserts', 'Bakery', 'Cafe'],
    rating: 4.9,
    deliveryTime: 22,
    priceForTwo: 300,
    diet: 'Veg',
    offer: '30% OFF on cakes',
    promoted: true,
    location: 'Midtown',
  },
  {
    id: 'r8',
    name: 'Ramen Republic',
    slug: 'ramen-republic',
    image: '/images/food-ramen.png',
    cuisines: ['Japanese', 'Ramen', 'Asian'],
    rating: 4.6,
    deliveryTime: 33,
    priceForTwo: 550,
    diet: 'Non-Veg',
    location: 'Harbor',
  },
  {
    id: 'r9',
    name: 'El Taco Loco',
    slug: 'el-taco-loco',
    image: '/images/food-tacos.png',
    cuisines: ['Mexican', 'Tacos', 'Street Food'],
    rating: 4.2,
    deliveryTime: 28,
    priceForTwo: 380,
    diet: 'Non-Veg',
    offer: 'Free drink on $20+',
    location: 'Old Town',
  },
  {
    id: 'r10',
    name: 'Juice & Co.',
    slug: 'juice-and-co',
    image: '/images/food-smoothie.png',
    cuisines: ['Beverages', 'Healthy', 'Vegan'],
    rating: 4.4,
    deliveryTime: 15,
    priceForTwo: 250,
    diet: 'Veg',
    location: 'Riverside',
  },
  {
    id: 'r11',
    name: 'Napoli Express',
    slug: 'napoli-express',
    image: '/images/restaurant-2.png',
    cuisines: ['Italian', 'Pizza', 'Fast Food'],
    rating: 4.1,
    deliveryTime: 24,
    priceForTwo: 320,
    diet: 'Veg',
    location: 'Midtown',
  },
  {
    id: 'r12',
    name: 'Urban Grill',
    slug: 'urban-grill',
    image: '/images/restaurant-1.png',
    cuisines: ['American', 'BBQ', 'Grill'],
    rating: 4.5,
    deliveryTime: 38,
    priceForTwo: 600,
    diet: 'Non-Veg',
    offer: '15% OFF',
    location: 'Downtown',
  },
]

function makeReviews(names: string[]): Food['reviews'] {
  const comments = [
    'Absolutely delicious, will order again!',
    'Great portion size and arrived hot.',
    'Packaging was neat and the taste was on point.',
    'A little pricey but worth every bite.',
    'My new favorite comfort food.',
  ]
  return names.map((n, i) => ({
    id: `rev-${n}-${i}`,
    name: n,
    rating: 4 + (i % 2 === 0 ? 1 : 0),
    date: ['2 days ago', '1 week ago', '3 weeks ago'][i % 3],
    comment: comments[i % comments.length],
  }))
}

export const foods: Food[] = [
  {
    id: 'f1',
    name: 'Margherita Pizza',
    slug: 'margherita-pizza',
    description:
      'Hand-tossed wood-fired pizza topped with San Marzano tomato sauce, fresh mozzarella, and hand-picked basil leaves. A timeless classic done right.',
    price: 12.99,
    image: '/images/food-pizza.png',
    rating: 4.6,
    reviewCount: 320,
    category: 'Pizza',
    cuisine: 'Italian',
    diet: 'Veg',
    spice: 'Mild',
    mood: ['Happy', 'Working', 'Party'],
    restaurantId: 'r1',
    restaurantName: 'Bella Napoli',
    ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Fresh basil', 'Olive oil'],
    nutrition: { calories: 850, protein: 32, carbs: 98, fat: 34 },
    reviews: makeReviews(['Aarav', 'Sofia', 'Leo']),
    popular: true,
  },
  {
    id: 'f2',
    name: 'Classic Cheeseburger',
    slug: 'classic-cheeseburger',
    description:
      'Juicy char-grilled beef patty with melted cheddar, crisp lettuce, tomato, pickles, and our signature smoky sauce in a toasted brioche bun.',
    price: 9.99,
    image: '/images/food-burger.png',
    rating: 4.4,
    reviewCount: 512,
    category: 'Burgers',
    cuisine: 'American',
    diet: 'Non-Veg',
    spice: 'Medium',
    mood: ['Happy', 'Tired', 'Party'],
    restaurantId: 'r2',
    restaurantName: 'The Burger Yard',
    ingredients: ['Beef patty', 'Cheddar cheese', 'Lettuce', 'Tomato', 'Brioche bun', 'Smoky sauce'],
    nutrition: { calories: 720, protein: 40, carbs: 52, fat: 38 },
    reviews: makeReviews(['Marcus', 'Priya', 'Diego']),
    popular: true,
  },
  {
    id: 'f3',
    name: 'Hyderabadi Chicken Biryani',
    slug: 'hyderabadi-chicken-biryani',
    description:
      'Fragrant basmati rice slow-cooked with tender marinated chicken, saffron, fried onions, and a blend of aromatic spices. Served with raita.',
    price: 14.5,
    image: '/images/food-biryani.png',
    rating: 4.7,
    reviewCount: 640,
    category: 'Biryani',
    cuisine: 'Indian',
    diet: 'Non-Veg',
    spice: 'Hot',
    mood: ['Happy', 'Party', 'Working'],
    restaurantId: 'r3',
    restaurantName: 'Spice Route',
    ingredients: ['Basmati rice', 'Chicken', 'Saffron', 'Fried onions', 'Yogurt', 'Biryani masala'],
    nutrition: { calories: 940, protein: 45, carbs: 110, fat: 30 },
    reviews: makeReviews(['Zara', 'Rohan', 'Mei']),
    popular: true,
  },
  {
    id: 'f4',
    name: 'Salmon Nigiri Platter',
    slug: 'salmon-nigiri-platter',
    description:
      'Twelve pieces of premium sushi and nigiri crafted with fresh salmon, tuna, and avocado. Served with wasabi, pickled ginger, and soy.',
    price: 18.0,
    image: '/images/food-sushi.png',
    rating: 4.8,
    reviewCount: 210,
    category: 'Sushi',
    cuisine: 'Japanese',
    diet: 'Non-Veg',
    spice: 'Mild',
    mood: ['Working', 'Party'],
    restaurantId: 'r4',
    restaurantName: 'Sakura House',
    ingredients: ['Sushi rice', 'Fresh salmon', 'Tuna', 'Avocado', 'Nori', 'Wasabi'],
    nutrition: { calories: 560, protein: 34, carbs: 70, fat: 14 },
    reviews: makeReviews(['Kenji', 'Nadia', 'Omar']),
    popular: true,
  },
  {
    id: 'f5',
    name: 'Rainbow Buddha Bowl',
    slug: 'rainbow-buddha-bowl',
    description:
      'A vibrant vegan bowl of quinoa, roasted chickpeas, avocado, cherry tomatoes, and seasonal greens tossed in a lemon-tahini dressing.',
    price: 11.5,
    image: '/images/food-salad.png',
    rating: 4.5,
    reviewCount: 180,
    category: 'Healthy',
    cuisine: 'Healthy',
    diet: 'Vegan',
    spice: 'Mild',
    mood: ['Working', 'Tired'],
    restaurantId: 'r5',
    restaurantName: 'Green Bowl',
    ingredients: ['Quinoa', 'Chickpeas', 'Avocado', 'Cherry tomatoes', 'Mixed greens', 'Tahini'],
    nutrition: { calories: 480, protein: 18, carbs: 62, fat: 20 },
    reviews: makeReviews(['Isla', 'Noah', 'Lea']),
    popular: true,
  },
  {
    id: 'f6',
    name: 'Creamy Alfredo Pasta',
    slug: 'creamy-alfredo-pasta',
    description:
      'Al dente penne pasta enveloped in a rich, velvety parmesan cream sauce, finished with cracked black pepper and fresh basil.',
    price: 10.75,
    image: '/images/food-pasta.png',
    rating: 4.3,
    reviewCount: 260,
    category: 'Pasta',
    cuisine: 'Italian',
    diet: 'Veg',
    spice: 'Mild',
    mood: ['Tired', 'Happy'],
    restaurantId: 'r6',
    restaurantName: 'Pasta Fresca',
    ingredients: ['Penne pasta', 'Parmesan', 'Cream', 'Garlic', 'Butter', 'Basil'],
    nutrition: { calories: 680, protein: 22, carbs: 84, fat: 30 },
    reviews: makeReviews(['Giulia', 'Sam', 'Ava']),
    popular: true,
  },
  {
    id: 'f7',
    name: 'Molten Chocolate Lava Cake',
    slug: 'molten-chocolate-lava-cake',
    description:
      'Warm chocolate cake with a gooey molten center, served with a scoop of vanilla bean ice cream and a handful of fresh berries.',
    price: 7.5,
    image: '/images/food-dessert.png',
    rating: 4.9,
    reviewCount: 430,
    category: 'Desserts',
    cuisine: 'Desserts',
    diet: 'Veg',
    spice: 'Mild',
    mood: ['Happy', 'Party', 'Tired'],
    restaurantId: 'r7',
    restaurantName: 'Sweet Ember',
    ingredients: ['Dark chocolate', 'Butter', 'Eggs', 'Flour', 'Vanilla ice cream', 'Berries'],
    nutrition: { calories: 520, protein: 8, carbs: 64, fat: 26 },
    reviews: makeReviews(['Chloe', 'Ben', 'Maya']),
    popular: true,
  },
  {
    id: 'f8',
    name: 'Tonkotsu Ramen',
    slug: 'tonkotsu-ramen',
    description:
      'A rich, slow-simmered pork bone broth with springy noodles, soft-boiled egg, chashu pork, nori, and scallions. Deeply comforting.',
    price: 13.25,
    image: '/images/food-ramen.png',
    rating: 4.6,
    reviewCount: 290,
    category: 'Ramen',
    cuisine: 'Japanese',
    diet: 'Non-Veg',
    spice: 'Medium',
    mood: ['Tired', 'Working'],
    restaurantId: 'r8',
    restaurantName: 'Ramen Republic',
    ingredients: ['Pork broth', 'Ramen noodles', 'Chashu pork', 'Soft egg', 'Nori', 'Scallions'],
    nutrition: { calories: 760, protein: 38, carbs: 88, fat: 28 },
    reviews: makeReviews(['Hiro', 'Elena', 'Tariq']),
    popular: true,
  },
  {
    id: 'f9',
    name: 'Street Style Tacos',
    slug: 'street-style-tacos',
    description:
      'Three soft corn tortillas loaded with grilled seasoned meat, fresh cilantro, diced onions, and a squeeze of lime. Spicy salsa on the side.',
    price: 8.75,
    image: '/images/food-tacos.png',
    rating: 4.2,
    reviewCount: 200,
    category: 'Mexican',
    cuisine: 'Mexican',
    diet: 'Non-Veg',
    spice: 'Hot',
    mood: ['Party', 'Happy'],
    restaurantId: 'r9',
    restaurantName: 'El Taco Loco',
    ingredients: ['Corn tortillas', 'Grilled meat', 'Cilantro', 'Onions', 'Lime', 'Salsa'],
    nutrition: { calories: 590, protein: 30, carbs: 56, fat: 24 },
    reviews: makeReviews(['Carlos', 'Fatima', 'Jack']),
  },
  {
    id: 'f10',
    name: 'Berry Blast Smoothie Bowl',
    slug: 'berry-blast-smoothie-bowl',
    description:
      'A thick blend of mixed berries and banana topped with granola, chia seeds, coconut flakes, and fresh fruit. Refreshing and energizing.',
    price: 6.99,
    image: '/images/food-smoothie.png',
    rating: 4.4,
    reviewCount: 150,
    category: 'Drinks',
    cuisine: 'Healthy',
    diet: 'Vegan',
    spice: 'Mild',
    mood: ['Happy', 'Working', 'Tired'],
    restaurantId: 'r10',
    restaurantName: 'Juice & Co.',
    ingredients: ['Mixed berries', 'Banana', 'Granola', 'Chia seeds', 'Coconut flakes'],
    nutrition: { calories: 380, protein: 10, carbs: 68, fat: 8 },
  },
  {
    id: 'f11',
    name: 'Pepperoni Feast Pizza',
    slug: 'pepperoni-feast-pizza',
    description:
      'A loaded pizza with double pepperoni, mozzarella, and a tangy tomato base on a crispy thin crust. For serious meat lovers.',
    price: 15.99,
    image: '/images/food-pizza.png',
    rating: 4.5,
    reviewCount: 275,
    category: 'Pizza',
    cuisine: 'Italian',
    diet: 'Non-Veg',
    spice: 'Medium',
    mood: ['Party', 'Happy'],
    restaurantId: 'r11',
    restaurantName: 'Napoli Express',
    ingredients: ['Pizza dough', 'Pepperoni', 'Mozzarella', 'Tomato base', 'Oregano'],
    nutrition: { calories: 980, protein: 42, carbs: 96, fat: 46 },
  },
  {
    id: 'f12',
    name: 'Smoky BBQ Ribs',
    slug: 'smoky-bbq-ribs',
    description:
      'Fall-off-the-bone pork ribs slow-smoked and glazed in a house-made smoky BBQ sauce. Served with fries and coleslaw.',
    price: 19.5,
    image: '/images/restaurant-1.png',
    rating: 4.5,
    reviewCount: 190,
    category: 'BBQ',
    cuisine: 'American',
    diet: 'Non-Veg',
    spice: 'Medium',
    mood: ['Party', 'Happy'],
    restaurantId: 'r12',
    restaurantName: 'Urban Grill',
    ingredients: ['Pork ribs', 'BBQ sauce', 'Fries', 'Coleslaw', 'Spice rub'],
    nutrition: { calories: 1050, protein: 55, carbs: 60, fat: 60 },
  },
]

export const offers: Offer[] = [
  {
    id: 'o1',
    title: '50% OFF',
    subtitle: 'On your first 3 orders',
    code: 'SMART50',
    color: 'from-orange-500 to-amber-500',
  },
  {
    id: 'o2',
    title: 'Free Delivery',
    subtitle: 'On orders above $15',
    code: 'FREEDEL',
    color: 'from-rose-500 to-orange-500',
  },
  {
    id: 'o3',
    title: 'Flat $8 OFF',
    subtitle: 'Pay using SmartBite Wallet',
    code: 'WALLET8',
    color: 'from-emerald-500 to-teal-500',
  },
]

export interface Promo {
  code: string
  type: 'percent' | 'flat' | 'freedel'
  value: number
  label: string
  minSubtotal: number
}

export const promoCodes: Record<string, Promo> = {
  SMART50: {
    code: 'SMART50',
    type: 'percent',
    value: 0.5,
    label: '50% off up to $10',
    minSubtotal: 20,
  },
  WALLET8: {
    code: 'WALLET8',
    type: 'flat',
    value: 8,
    label: '$8 off your order',
    minSubtotal: 25,
  },
  FREEDEL: {
    code: 'FREEDEL',
    type: 'freedel',
    value: 0,
    label: 'Free delivery',
    minSubtotal: 0,
  },
  SMARTBITE: {
    code: 'SMARTBITE',
    type: 'percent',
    value: 0.15,
    label: '15% off your order',
    minSubtotal: 0,
  },
}

export const cuisineList = Array.from(
  new Set(restaurants.flatMap((r) => r.cuisines)),
).sort()

export function getRestaurantBySlug(slug: string) {
  return restaurants.find((r) => r.slug === slug)
}

export function getFoodBySlug(slug: string) {
  return foods.find((f) => f.slug === slug)
}

export function getFoodsByRestaurant(restaurantId: string) {
  return foods.filter((f) => f.restaurantId === restaurantId)
}

export function getRecommendedFoods(excludeId: string, limit = 6) {
  return foods.filter((f) => f.id !== excludeId).slice(0, limit)
}
